name: "Publish package to npm"

on:
  workflow_dispatch:

jobs:
  build_and_publish_release:
    runs-on: ubuntu-latest
    environment: production

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Set npm auth token
        run: |
          echo npmAuthToken: "$NPM_TOKEN" >> ./.yarnrc.yml
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build package
        run: yarn build

      - name: Publish
        run: yarn npm publish
